[project]
name = "noise"
version = "0.1.0"
description = "Noise detector using audio analysis"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "pyarrow",
    "sounddevice",
    "torch",
    "torchaudio",
]
